routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('events','EventController');
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Event extends Model 
{
    protected $table = 'events';
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use LaravelFullCalendar\Facades\Calendar;

class EventController extends Controller
{
    public function index()
    {

        $events = Event::all();
        $event = [];

        foreach ($events as $raw) {
            $event[] = Calendar::event(
                $raw->title,
                false, // for timing
                new \DateTime($raw->start_date),
                new \DateTime($raw->end_date),
                $raw->id,
                [
                    'color' => $raw->color
                ]

            );
        }

        $calendar = Calendar::addEvents($event);


        return view('events.index', compact('calendar','events'));
    }

    public function create()
    {

        return view('events.create');

    }//end of create function

    public function store(Request $request)
    {

        $data = $request->validate([
            'title' => 'required',
            'color' => 'required',
            'start_date' => 'required|date|after_or_equal:' . Carbon::now()->toDateString(),
            'end_date' => 'required|date'
        ]);

        Event::create($data);

        return redirect()->route('events.index')->with('success', 'data stored successfully');
    }//end of store function

    public function edit($id){

        $event = Event::find($id);
        return view('events.edit',compact('event'));

    }//end of edit function

    public function update(Request $request,$id){

        $event =Event::find($id);
        $data = $request->validate([
            'title' => 'required',
            'color' => 'required',
            'start_date' => 'required|date|after_or_equal:' . Carbon::now()->toDateString(),
            'end_date' => 'required|date'
        ]);
        $event->update($data);
        return redirect()->route('events.index')->with('success', 'data stored successfully');

    }//end of update function

    public function destroy ($id){

        $event = Event::find($id);
        $event->delete();
        return redirect()->route('events.index')->with('success', 'data stored successfully');

    }//end of destroy  function
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/events/create.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>
</head>
<body>

<div class="container" style="margin-top: 100px">

    @if($errors->any())

        @foreach($errors->all() as $error)

            <div class="alert alert-danger">{{$error}}</div>
        @endforeach
    @endif
    <div class="row">


            <form action="{{route('events.store')}}" class="form" method="post">
                @csrf
                <div class="form-group">
                    <label for="" class="form-label">Title</label>
                    <input type="text" class="form-control" name="title">
                </div>

                <div class="form-group">
                    <label for="" class="form-label">Color</label>
                    <input type="color" class="form-control" name="color">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Start Date</label>
                    <input type="datetime-local" class="form-control" name="start_date">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">End Date</label>
                    <input type="datetime-local" class="form-control" name="end_date">
                </div>

                <div class="form-group mt-2">
                    <button type="submit" class="btn btn-success form-control">Save</button>
                </div>
            </form>



    </div>
</div>

</body>
</html>

resources/views/events/edit.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>
</head>
<body>

<div class="container" style="margin-top: 100px">

    @if($errors->any())

        @foreach($errors->all() as $error)

            <div class="alert alert-danger">{{$error}}</div>
        @endforeach
    @endif
    <div class="row">



        <form action="{{route('events.update',$event->id)}}" class="form" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="" class="form-label">Title</label>
                <input type="text" value="{{$event->title}}" class="form-control" name="title">
            </div>

            <div class="form-group">
                <label for="" class="form-label">Color</label>
                <input type="color" value="{{$event->color}}" class="form-control" name="color">
            </div>
            <div class="form-group">
                <label for="" class="form-label">Start Date</label>
                <input value="{{\Carbon\Carbon::make($event->start_date)->toDateTimeLocalString()}}" type="datetime-local"  class="form-control" name="start_date">
            </div>
            <div class="form-group">
                <label for="" class="form-label">End Date</label>
                <input type="datetime-local" value="{{\Carbon\Carbon::make($event->end_date)->toDateTimeLocalString()}}" class="form-control" name="end_date">
            </div>

            <div class="form-group mt-2">
                <button type="submit" class="btn btn-success form-control">Save</button>
            </div>
        </form>



    </div>
</div>

</body>
</html>

resources/views/events/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>

    {{--    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>--}}
    {{--    <script src="https://kit.fontawesome.com/2eb6657f57.js" crossorigin="anonymous"></script>--}}
    {{--    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.css"/>--}}

    <link rel="stylesheet" href="{{asset('plugins/calendar/main.min.css')}}">
    <script src="{{asset('plugins/calendar/main.min.js')}}"></script>

</head>
<body>

<h4 class="text-center mt-2 mb-2"> Full calendar</h4>


<div class="container">
    <div id='calendar'></div>
</div>

<div class="container" style="width: 800px ;height: 800px">
    <div id="dialog">
        <div id="dialog-body">
            <form method="post"  action="{{route('events.store')}}" id="dayClick">
                @csrf
                <div class="form-group">
                    <label for="" class="form-label">Title</label>
                    <input type="text" class="form-control" name="title">
                </div>

                <div class="form-group">
                    <label for="" class="form-label">Start Date</label>
                    <input type="text" class="form-control" name="start">
                </div>

                <div class="form-group">
                    <label for="" class="form-label">End Date</label>
                    <input type="text" class="form-control" name="end">
                </div>

                <div class="form-group">
                    <label class="form-check-inline" for="">All Day</label>
                    <input type="checkbox" value="1" class="form-check-input" name="allDay"> All Day
                    <input type="checkbox" value="0" class="form-check-input" name="allDay"> Partial
                </div>

                <div class="form-group">
                    <label for="" class="form-label">Color</label>
                    <input type="color" class="form-control" name="color">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Color Text</label>
                    <input type="color" class="form-control" name="text_color">
                </div>
            </form>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        var calendar = $('#calendar').fullCalendar({
            height: 800,
            defaultView: 'month',
            editable: false,
            showNonCurrentDates: false,
            yearColumns: 3,
            selectable:true,

            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'year,month,basicWeek,basicDay'
            },
            dayClick:function (date,event,view){
                    alert(view)
            }


        })


    })
</script>


{{--<div class="container m-2">--}}
{{--    <a href="{{route('events.create')}}" class="btn btn-success">Create Event </a>--}}
{{--    <a href="" class="btn btn-primary">Edit Event </a>--}}
{{--    <a href="" class="btn btn-danger">Delete Event </a>--}}
{{--</div>--}}
{{--<div class="container" style="width: 1000px; height: 1000px">--}}

{{--    <div class="row">--}}
{{--        <div class="col-md-8">--}}
{{--            {!! $calendar->calendar() !!}--}}
{{--            {!! $calendar->script() !!}--}}
{{--        </div>--}}
{{--        <div class="col-md-4">--}}
{{--            <h5>Events</h5>--}}
{{--            <table class="table table-hover table-bordered text-center">--}}
{{--                <thead>--}}
{{--                <th>#</th>--}}
{{--                <th>Title</th>--}}
{{--                <th>Actions</th>--}}
{{--                </thead>--}}

{{--                @foreach($events as $index=> $event)--}}
{{--                    <tbody>--}}
{{--                    <tr>--}}
{{--                        <td>{{++$index}}</td>--}}
{{--                        <td>{{$event->title}}</td>--}}
{{--                        <td>--}}
{{--                            <a href="{{route('events.edit',$event->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-edit fa-sm"></i></a>--}}
{{--                            <form  method="post" action="{{route('events.destroy',$event->id)}}">--}}

{{--                                @csrf--}}
{{--                                @method('delete')--}}
{{--                              <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash fa-sm"></i></button>--}}
{{--                            </form>--}}

{{--                        </td>--}}
{{--                    </tr>--}}
{{--                    </tbody>--}}
{{--                @endforeach--}}


{{--            </table>--}}
{{--        </div>--}}
{{--    </div>--}}


{{--</div>--}}


<script>

</script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>